service: blog-service-new
frameworkVersion: "3"

provider:
  name: aws
  runtime: nodejs20.x
  region: us-east-1
  stage: dev
  stackName: Blog-Service-New
  role: arn:aws:iam::050752626146:role/ExecutionRoleForS3AndLambda
  memorySize: 1024
  timeout: 29
  versionFunctions: false
  endpointType: regional
  tracing:
    lambda: true
  stackTags:
    environment: dev
  iamRoleStatements:
    - Effect: Allow
      Action:
        - lambda:InvokeFunction
      Resource: "*"
    - Effect: Allow
      Action:
        - "sns:Publish"
        - "sqs:SendMessage"
      Resource:
        - { "Fn::GetAtt": ["BlogQueue", "Arn"] }
        - { "Fn::GetAtt": ["BlogSnsTopic", "Arn"] }
functions:
  AddNewBlog:
    handler: handler.addNewBlog
    description: Add New Blog function
    name: add-new-blog
    environment:
      XRAY_ENABLED: true
      STAGE: dev
      DATABASE_URL: mongodb+srv://vishwakarma137:nQc7HjtfDSaB19Db@blog-app.a414a.mongodb.net/?retryWrites=true&w=majority&appName=Blog-App
      DB_NAME: blogs
      JWT_KEY: secret
      SNS_TOPIC_ARN: arn:aws:sns:us-east-1:050752626146:BlogSnsTopic
    events:
      - http:
          path: /blog
          method: post
          cors: true
          authorizer:
            arn: arn:aws:lambda:us-east-1:050752626146:function:authorizer-test-dev-authorizeJwtToken
  GetAllBlogs:
    handler: handler.getAllBlogs
    description: Get all blogs function
    name: get-all-blogs
    environment:
      XRAY_ENABLED: true
      STAGE: dev
      DATABASE_URL: mongodb+srv://vishwakarma137:nQc7HjtfDSaB19Db@blog-app.a414a.mongodb.net/?retryWrites=true&w=majority&appName=Blog-App
      DB_NAME: blogs
      JWT_KEY: secret
    events:
      - http:
          path: /blog
          method: get
          cors: true
          authorizer:
            arn: arn:aws:lambda:us-east-1:050752626146:function:authorizer-test-dev-authorizeJwtToken
  GetBlogById:
    handler: handler.getBlogById
    description: Get blog by id function
    name: get-blog-by-id
    environment:
      XRAY_ENABLED: true
      STAGE: dev
      DATABASE_URL: mongodb+srv://vishwakarma137:nQc7HjtfDSaB19Db@blog-app.a414a.mongodb.net/?retryWrites=true&w=majority&appName=Blog-App
      DB_NAME: blogs
      JWT_KEY: secret
    events:
      - http:
          path: /blog/{id}
          method: get
          cors: true
          authorizer:
            arn: arn:aws:lambda:us-east-1:050752626146:function:authorizer-test-dev-authorizeJwtToken
  DeleteBlog:
    handler: handler.deleteBlog
    description: Delete blog function
    name: delete-blog
    environment:
      XRAY_ENABLED: true
      STAGE: dev
      DATABASE_URL: mongodb+srv://vishwakarma137:nQc7HjtfDSaB19Db@blog-app.a414a.mongodb.net/?retryWrites=true&w=majority&appName=Blog-App
      DB_NAME: blogs
      JWT_KEY: secret
    events:
      - http:
          path: /blog/{id}
          method: delete
          cors: true
          authorizer:
            arn: arn:aws:lambda:us-east-1:050752626146:function:authorizer-test-dev-authorizeJwtToken
  ProcessBlogQueue:
    handler: handler.processBlogQueue
    description: Process Blog Queue function
    events:
      - sqs:
          arn:
            "Fn::GetAtt": ["BlogQueue", "Arn"]
          batchSize: 10
resources:
  Resources:
    GatewayResponseDefault4XX:
      Type: "AWS::ApiGateway::GatewayResponse"
      Properties:
        ResponseParameters:
          gatewayresponse.header.Access-Control-Allow-Origin: "'*'"
          gatewayresponse.header.Access-Control-Allow-Headers: "'Content-Type,Authorization'"
        ResponseType: DEFAULT_4XX
        RestApiId:
          Ref: "ApiGatewayRestApi"
    GatewayResponseDEFAULT5XX:
      Type: "AWS::ApiGateway::GatewayResponse"
      Properties:
        ResponseParameters:
          gatewayresponse.header.Access-Control-Allow-Origin: "'*'"
          gatewayresponse.header.Access-Control-Allow-Headers: "'Content-Type,Authorization'"
        ResponseType: DEFAULT_5XX
        RestApiId:
          Ref: "ApiGatewayRestApi"
    BlogSnsTopic:
      Type: AWS::SNS::Topic
      Properties:
        TopicName: "BlogSnsTopic"
    BlogQueue:
      Type: AWS::SQS::Queue
      Properties:
        QueueName: "BlogQueue"
        VisibilityTimeout: 30
    BlogQueueSubscription:
      Type: AWS::SNS::Subscription
      Properties:
        TopicArn:
          Ref: BlogSnsTopic
        Protocol: "sqs"
        Endpoint:
          "Fn::GetAtt": ["BlogQueue", "Arn"]
    BlogQueuePolicy:
      Type: AWS::SQS::QueuePolicy
      Properties:
        Queues:
          - Ref: BlogQueue
        PolicyDocument:
          Version: "2012-10-17"
          Statement:
            - Effect: Allow
              Action:
                - "sqs:SendMessage"
              Principal: "*"
              Resource:
                "Fn::GetAtt": ["BlogQueue", "Arn"]
              Condition:
                ArnEquals:
                  aws:SourceArn:
                    Ref: BlogSnsTopic
    SnsToSqsSubscription:
      Type: "AWS::SNS::Subscription"
      Properties:
        TopicArn:
          Ref: BlogSnsTopic
        Protocol: "sqs"
        Endpoint:
          "Fn::GetAtt": ["BlogQueue", "Arn"]
  Outputs:
    BlogSnsTopicArn:
      Description: Blog Topic ARN for SNS topic
      Value:
        Ref: BlogSnsTopic
    BlogQueueArn:
      Description: Blog Queue ARN for SQS queue
      Value:
        "Fn::GetAtt": ["BlogQueue", "Arn"]
package:
  exclude:
    - coverage/**
    - test/**
    - package-lock.json
    - .npm/**
    - .idea/**
